#!/bin/sh -e
# Copyright (c) 2017 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

APPLICATION="${0##*/}"

USAGE="$APPLICATION [options]


Wraps enter-chroot to start a Kodi session.
Wraps enter-chroot to start an KODI session.
By default, it will log into the primary user on the first chroot found.

Options are directly passed to enter-chroot; run enter-chroot to list them."

#<<<<<<< HEAD
#exec sh -e "`dirname "\`readlink -f "$0"\`"`/enter-chroot" -t kodi "$@" "" \
#    exec xinit /usr/bin/kodi
#=======
exec sh -e "`dirname "\`readlink -f -- "$0"\`"`/enter-chroot" -t kodi "$@" "" \
    exec croutonpowerd -i xinit /usr/bin/kodi --standalone
#>>>>>>> 67dc8d77d44552b05ab6ad2fc7d699e2d4003064
